# Generated by Django 5.1.2 on 2025-05-13 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('solution', models.TextField(verbose_name='Решение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Анонимное решение',
                'verbose_name_plural': 'Анонимные решения',
            },
        ),
        migrations.CreateModel(
            name='GeneratedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(max_length=255, null=True, verbose_name='Хеш-код варианта')),
                ('anonymous_solutions', models.ManyToManyField(blank=True, related_name='generated_tasks', to='generatedTask.anonymoussolution', verbose_name='Анонимные решения')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Получатели')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
    ]
