# Generated by Django 5.1.2 on 2025-05-31 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(max_length=255, null=True, verbose_name='Хеш-код варианта')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Получатели')),
                ('tasks', models.ManyToManyField(blank=True, related_name='generated_tasks', to='tasks.task', verbose_name='Задания')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(max_length=255, null=True, verbose_name='Хеш-код варианта')),
                ('decryption_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ дешифровки')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_training_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('tasks', models.ManyToManyField(blank=True, related_name='training_tasks', to='tasks.task', verbose_name='Задания')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тренировочный вариант',
                'verbose_name_plural': 'Тренировочные варианты',
            },
        ),
    ]
