# Generated by Django 5.1.2 on 2025-05-13 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generatedTask', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Выполнено'), ('in_progress', 'В процессе'), ('not_started', 'Не начато')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('time_spent', models.DurationField(blank=True, null=True, verbose_name='Время выполнения')),
                ('generated_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generatedTask.generatedtask', verbose_name='Вариант')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус задания',
                'verbose_name_plural': 'Статусы заданий',
            },
        ),
    ]
