export const PATHS = {
  HOME: '/',
  PROFESSOR: '/professor',
  PROFESSOR_OPTION: '/professor/:option',
  PROFESSOR_TASK: '/professors/integrals',
  STUDENT: '/student',
  STUDENT_OPTION: '/student/:option',
  OPTION: '/option',
  ABOUT: '/about',
  LOGIN: '/login',
  QR: '/qr',
  REGISTER: '/register',
  MY_ANSWERS: '/my-answers',
  GET_VARIANT: '/get-variant',
  TASKS: '/tasks',
  ADD_TASK: '/add-task',
  THEMES: '/themes',
  PROFILE: '/profile',
  TASK_STATUS: '/taskstatus',
  TASK: '/task'
} as const;
